FROM php:8.3-fpm

WORKDIR /var/www/backend

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    libpq-dev \
    git \
    curl \
    && docker-php-ext-install pdo_pgsql

# Copiar código
COPY backend/ .

# Instalar composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar dependencias PHP
RUN composer install --no-dev --optimize-autoloader

# Comando para correr la app
CMD ["php-fpm"]
